apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ticket-management.fullname" . }}-secrets
type: Opaque
stringData:
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
  jwt-key: {{ .Values.secrets.jwtKey | quote }}
