apiVersion: v1
kind: Service
metadata:
  name: {{ include "ticket-management.fullname" . }}-ui
spec:
  type: NodePort
  selector:
    app: {{ include "ticket-management.fullname" . }}-ui
  ports:
    - port: {{ .Values.ui.port }}
      targetPort: {{ .Values.ui.port }}
