#!/bin/sh

echo "Running backend checks..."
dotnet build && dotnet test || exit 1

echo "Running frontend checks..."
cd TicketManagement.Ui || exit 1

npm run lint &&
npm run format:check &&
npm test -- --run &&
npm run build
